### ISSUE TITLE
Prince of Persia - The Sands of Time: Green bar on top screen edge

### ISSUE THREAD

**Issue by thrimbor** [xqemu/xqemu#123]
Possibly related to #124.

"Prince of Persia: The Sands of Time" shows a green bar on the top edge of the screen. The area where the bar appears and the color are always the same.

![pop tsot](https://user-images.githubusercontent.com/1339483/47593943-9d696380-d979-11e8-863d-034660a1a43f.png)

Tested on Arch Linux (GTX 970, nvidia 410.66-1) and Windows 7 (GeForce 310M).

More screenshots available [here](https://nextcloud.improved-madness.de/index.php/s/p3gsLQzXY2HNXt7)

**Comment by JayFoxRox** [comment]
It's an off by one in a screen-space scene-brightness texture which is scaled as far down as 10x7 pixels.
It's sampled in resolutions 10x7, 20x15, 40x30, 80x60 in texture units 0 to 3 respectively. So it's safe to assume that this is some form of HDR / Bloom buffer.

The broken pixel line (from a source image at 640x480 which will be downsampled iteratively) has color 16,128,16,128 (RGBA) which is a dark green line.

It seems to be generated from an off-by-one in the original framebuffer used for 3D, of color 227,44,70,0 (RGBA) which is a wine-red line. The framebuffer is cleared to that color on frame start (done by `glClear` in XQEMU).

The clip-region is probably the culprit here, because scissor testing is disabled, so this is our only way of cutting off the frame like this (for 3D objects).

While rendering the 3D scene we have the following `clipRegion[0]`: (0, -1, 640, 479)

Someone should probably unit-test the clipping behaviour on a real Xbox using nxdk.
We'll also need to review our clipping code while anti-aliasing is active, so we'd need a test sooner-or later anyway.

*Regardless of the off-by-one issue, the scene-brightness texture appears to contain garbage (only 4 random pixels are highlighted aside from the off-by-one). I'm not sure why that is.*
