### ISSUE TITLE
nothing beyond 1.0 is supported

### ISSUE THREAD

**Issue by JazzMaster** [xqemu/xqemu#136]
since its impossible to find 1.0 or factory restored hard drives- (yeah, I know yall have it) because of all the modding going on, and v1 xbox es are equally impossible to find-

Im filing this bug. (It should serve notice to those testing your code as well)

versions above 1.0 need to be accomadated for, including bioses and eeproms.

If you have the contents of a console above 1.0 it wont boot. 
Period. 

Furthermore you need the ORIGINAL HDD content, not locked at all. 
Providing "unrestricted files" does nothing if nobody can boot those. And they cannot with the stock bios you reference. Links are down everywhere. Telling us "to fetch" is not an option. You are basically telling us to hack our boxes just like some of you (with mm precision)- not everyone is awesome at this.

Either provide a working BIOS (situation) or provide the full xbox original unmodified HDD.
This is legal under US law under "copywright exemption for personal use". You arent redistributing or modifying anything. You are just providing the HDD in its original format -in a file.
As long as you own an xbox- owning a copy of the HDD contents is legal. RESEARCH and DEVELOPMENT purposes allow copies also. So dont gimmie that YOU CANT INCLUDE IT garbage.
You are providing a proof of concept emulation system "in accordance with original microsoft specifications".

Furthermore- you can provide the files and utils as an alternative to the HDD image, which GH refuses to host based on size.

You arent covering anyones six by skimping here. You are preventing people from testing, demo-ing, and keeping up with your progress. This harms development.

HDD contents:
UNMODIFIED ORIGINAL CONTENTS, NO SOFTMODS.

Qemu handles the locking. This is undocumented. No feature should be.

You tell qemu to use a locked HDD but --
      If using xboxhdm to make one from files- YOU DO NOT LOCK IT. DO NOT USE AN EEPROM.

-Strangely this works.

The bioses above 1.0 give more accurate response codes other than not working- to avoid them is confuse people with solveable errors.

Code 14,17 which pop on hardware above 1.0 indicate missing or misconfigured drives for example. xqemu doesnt seem to care with the 1.0. GENERAL ERROR is the modus operandi and thats just wrong.

How would you like every compiler error to be like that? This is how you are treating those trying to test or develop(and keep up with you).

wether modified bioses or debug ones work is unknown- nobody can find them. So that means either all of you are file sharing in secret- or you know EVERYTHING about the xbox-O and just arent coming forth with it. I prefer the former examination. I suggest you come clean- because you havent been on the scene half as long as me nor my collegues.

**Comment by JayFoxRox** [comment]
> nothing beyond 1.0 is supported
> since its impossible to find 1.0

- What does that even mean?
- What do you mean by "support"?

And what does 1.0 even refer to?

- Xbox 1.0? That's hardware..
- MCPX X3 ROM 1.0?
- EEPROM for Xbox 1.0?
- Flash compatible with Xbox 1.0?
- XQEMU 1.0?

It's really hard to understand what you even mean.

We do support many things for Xbox 1.1+; we *only* actively support XQEMU 3.x+, etc.

> or factory restored hard drives- (yeah, I know yall have it) because of all the modding going on, and v1 xbox es are equally impossible to find-

See my response in #135. We provide a working HDD image.

> If you have the contents of a console above 1.0 it wont boot.

Not true (to my knowledge). I can check again later, but you'll have to be more precise, which part of a 1.0 would be making trouble.

The only revision we don't really support is 1.6, and maybe 1.4/1.5, because of their video encoders.
Even USB which was changed between revisions shouldn't really be an issue.

> Furthermore you need the ORIGINAL HDD content, not locked at all.

This is not true. A dummy HDD is enough (as is for booting a real Xbox).

Locking also doesn't affect disk contents - XQEMU doesn't care if your virtual drive is locked or not.
XQEMU emulates a locked drive so the kernel can feel happy about successfully "unlocking" it.

> And they cannot with the stock bios you reference. Links are down everywhere.

We don't link to anything because it would be illegal. And as I've already explained in #135, we do not condone piracy.

*In fact, I'm tempted to report you to GitHub support because you've named a piracy website.*

> You are basically telling us to hack our boxes just like some of you (with mm precision)- not everyone is awesome at this.

Again: We'd love to make this easier, but we can't do it legally or without tremendous amount of work.

We provide free software - you don't get to complain. If you want to make it easier to use, you are welcome to contribute code or documentation.

> Either provide a working BIOS (situation) or provide the full xbox original unmodified HDD.
> This is legal under US law under "copywright exemption for personal use". You arent redistributing or modifying anything. You are just providing the HDD in its original format -in a file.

Right... so if I go to a cinema, pay my entrance fee, I can just whip out a camera and film the movie? As long as I upload the unedited footage that's legal?

This is just plain wrong.

We can't provide a bios legally. We are happy to explain how to dump things, but it's tricky and we can't give a "technology 101".

> As long as you own an xbox- owning a copy of the HDD contents is legal.

Again: This is wrong.

You are allowed to make a backup of *your* HDD. But you can't just download someones elses HDD image.
Even if it was legal (it is in some places), we still wouldn't share these files publicly because we couldn't verify you have the right to download it.

Instead, we mention tools to dump these files, or we provide free / open-source alternatives.
We could highlight this better, but again: we don't have enough active contributors to do so - contributions are welcome.

> You arent covering anyones six by skimping here. You are preventing people from testing, demo-ing, and keeping up with your progress. This harms development.

That's why we are trying to be supportive when someone asks how to run XQEMU, why we address bugs users find, and why we not only work on Xbox *emulation* but also Xbox exploit search and an Xbox kernel re-implementation.

> Qemu handles the locking. This is undocumented. No feature should be.

This is irrelevant to users. We also don't explain that the Xbox has an SMC as watchdog - it's true, but it's not relevant to our users. It doesn't change what kind of image-dumps you need, or how you run the emulator.

The only time it makes a difference, is when you hook up an actual Xbox HDD to XQEMU. However, we don't document this anywhere because it's unsupported and quite advanced.
Barely anyone running XQEMU intends to hook up their actual Xbox HDD probably - most people don't even have IDE ports anymore.

> wether modified bioses or debug ones work is unknown- nobody can find them.

If your bios works on a real Xbox, then chances are it will run in XQEMU.

> So that means either all of you are file sharing in secret

We don't need to share anything in secret.. we share what we can legally share, and users of XQEMU can dump their own Xbox contents to get the rest (namely flash + MCPX ROM + game XISOs).

> I suggest you come clean- because you havent been on the scene half as long as me nor my collegues.

What does that even mean?
If you have been around so long, then you should know how to dump MCPX ROM and flash.

What "scene"?
I also don't recognize your name, and I'm not aware of *you* contributing to projects like ours which benefit the Xbox and emulation communities.
XQEMU and XboxDev community members have contributed many tools, software and knowledge.


---

Again: This is going absolutely nowhere.

This is also a warning: if you keep promoting piracy or remain hostile towards members of our communities, you'll be banned and reported to GitHub support.

Closed.
