### ISSUE TITLE
windows xqemu demands a certain bios file

### ISSUE THREAD

**Issue by JazzMaster** [xqemu/xqemu#229]
I noticed under wine that xqemu is demanding a certain type (256) of bios file. I will look into msft compiling once I get win7 setup again. This shows that windows dev is not on par w linux dev- which is wrong.

Build process is different- however--the resulting output binary should otherwise be the same--from the same codebase- minus the arch and os differences.

While xbins(offline- you need to find the "distribution") gives you multiple bios files to test with-we shouldnt ask for a certain one- nor should the project only work with one. There are several in fact -that work nicely.

If you are running softmod- you have stock bios. Its loading a modified dash.

**Comment by dracc** [comment]
"certain type (256)"? What? I run with a 1M bios dump regularly if file size is what you're on about?

**Comment by mborgerson** [comment]
> I noticed under wine that xqemu is demanding a certain type (256) of bios file. I will look into msft compiling once I get win7 setup again. This shows that windows dev is not on par w linux dev- which is wrong.
> 
> Build process is different- however--the resulting output binary should otherwise be the same--from the same codebase- minus the arch and os differences.

Windows and Linux builds of XQEMU have uniform compatibility with different BIOS images. Windows does should not *demand* any specific file. Can you point to the specific error message you're observing? Can you re-file with the specific error in question?

Also please note that we do not claim to support running XQEMU built for Windows on Linux via Wine. AFAIK nobody has even tried this. I'm interested to see what the results are, but apparently it's not so great.

> This shows that windows dev is not on par w linux dev

This is true. We need more Windows developers on this project. However, Windows users have reported success with XQEMU and it's nearly on-par with Linux (notable difference is that Linux has better support for acceleration via KVM, but there are less-stable/slower virtualization solutions available on Windows).

> While xbins(offline- you need to find the "distribution") gives you multiple bios files to test with-we shouldnt ask for a certain one- nor should the project only work with one. There are several in fact -that work nicely.

XQEMU is compatible with 1.0 Xbox BIOS images, we state this explicitly. However, because we fail to implement some hardware security features--unmodified images may have issues. You are welcome to help improve this and file a PR!

Also please note that we specifically do not endorse or promote piracy. __Please do not suggest places to get illegally distributed content.__

> If you are running softmod- you have stock bios. Its loading a modified dash.

Yes, "softmods" should all work as expected.
