### ISSUE TITLE
Wrong gamepad mapping in WWE RAW2

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [xqemu/xqemu#77]
Wrong gamepad mapping in WWE RAW2 - game shows that pad3 is connected instead of pad1

![image](https://user-images.githubusercontent.com/24764335/42501377-47d9dfea-843c-11e8-89a9-6a5cceae1bc3.png)

Pad-related launch parameters:
`-usb -device usb-xbox-gamepad`

**Comment by JayFoxRox** [comment]
This actually affects *all* games and is something we should fix.
There's [a workaround on xqemu.com](https://xqemu.com/input/#advanced-info) but to my knowledge it doesn't work with the current master revision + it shouldn't be in the advanced section.

All of our command line examples and frontends should map this properly in the future.

**Comment by dracc** [comment]
I believe this has actually been fixed?

**Comment by JayFoxRox** [comment]
Yes. It has never been a problem in the first place, as hinted in my previous post (command line implicitly hooks it up to port for player 3).

I'm not sure why I called it a workaround.
What might have been the case was that the command line was temporarily not working due to QEMU 1 to QEMU 2 migration.
Anyhow, this is an issue with xqemu.com not documenting it correctly, but it isn't an issue with xqemu itself (not all sample command lines map it correctly).

With XQEMU-Manager it's much harder to do this incorrectly, too.

Closing.
