### ISSUE TITLE
Add option to apply modern post-processing anti-aliasing technique on framebuffer

### ISSUE THREAD

**Issue by mborgerson** [xqemu/xqemu#9]
Idea is to leverage some relatively recent developments in anti-aliasing research, namely [SMAA](http://www.iryoku.com/smaa/) ([shader](https://github.com/iryoku/smaa/blob/master/SMAA.hlsl)). This technique can be applied to an image, so even CPU blt'd images can benefit from this.

**Comment by JayFoxRox** [comment]
This belongs in a fork, external tool, graphics driver or elsewhere in my opinion.

XQEMU has enough trouble emulating games properly, and this is almost purely a post-processing step.
It's also questionable wether this is still required if we have a surface cache and can render at higher internal resolutions (and the image could be downsized for final display).

**Comment by mborgerson** [comment]
Strongly against forking xqemu, which would further fragment Xbox emulation.

Eventually, yes we should be able to render at higher resolutions. Rendering at higher resolutions and downsizing is the classic method of antialiasing, but new techniques can let us avoid the costs of higher rendering resolutions and simply enable a much less expensive post processing stage before display which could of course could be enabled or disabled.

**Comment by JayFoxRox** [comment]
> Strongly against forking xqemu, which would further fragment Xbox emulation.

I think it's fine if the fork only provides a thin layer and keeps in touch with upstream, but doesn't do any emulation changes.
Consider it a set of patches for niche features or which would otherwise distract from working towards the primary goal (Xbox emulation).
Much like [Ishiiruka changes stuff in Dolphin](https://forums.dolphin-emu.org/Thread-unofficial-ishiiruka-dolphin-custom-version), but barely contributes to emulation.

Most of these changes could also happen in a frontend or wrapper around the emulator.
As long as it's cleanly seperated from the main code, and does not take any maintenance effort, I'm fine with it.
But features which are not necessary or directly beneficial for Xbox emulation, but take a maintainers time, should be avoided at all costs, or run in a seperate project (possibly under the official XQEMU name).

> post processing stage before display 

The final display can typically optimized system-wide by your graphics driver (usually a graphics-quality setting) or seperate hooks.
Some drivers even support internal upscaling now, but it doesn't work well for emulation as our surfaces might leave the GPU temporarily (+ we get our own for free with a surface cache).

**Comment by mborgerson** [comment]
I did prototype this, and while it provided decent results for low-resolution rendering (640x480), it pales in comparison to what I was able to achieve with native surface scaling for higher resolution rendering--while still maintaining a high level of performance.

I believe there may still be space for improving emulation graphics quality through post-processing or other techniques (for example, I was able to use machine learning to upscale textures with [pretty inspiring results](https://imgur.com/a/uGlXWFG)), but I consider those to be out of scope for the time being.

For these reasons, I'm closing this issue and focusing on other directions.
